apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: platform
data:
  config.yaml: |
    metrics: 0.0.0.0:2000

    ingress:
      # Route all traffic to Istio IngressGateway
      - service: http://istio-ingressgateway.istio-system.svc.cluster.local:80
        originRequest:
          noTLSVerify: true
          httpHostHeader: ""
