apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: platform
data:
  config.yaml: |
    tunnel: 24ca1f2b-5a12-497b-bdb0-49496fde9bc8
    credentials-file: /etc/cloudflared/token
    metrics: 0.0.0.0:2000
    no-autoupdate: true

    ingress:
      # Route all traffic to Istio IngressGateway
      - service: http://istio-ingressgateway.istio-system.svc.cluster.local:80
        originRequest:
          noTLSVerify: true
          httpHostHeader: ""
