---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bigbang
  namespace: bigbang
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: bigbang
    namespace: bigbang
  path: ./base
  prune: true
  wait: true
  timeout: 20m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: bigbang-values
