apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gitrepository.yaml
  - fluxkustomization.yaml

configMapGenerator:
  - name: bigbang-values
    namespace: bigbang
    files:
      - values.yaml=values/sandbox.yaml
